### ISSUE TITLE
Compiling elsa makes tests stop working

### ISSUE THREAD

**Issue by DamienCassou** [emacs-elsa/Elsa#111]
My Emacs setup (using [borg](https://github.com/emacscollective/borg)) compiles by default all packages I install. This doesn't work for Elsa on Emacs 26.1 as demonstrated by #110 and [its travis output](https://travis-ci.org/emacs-elsa/Elsa/builds/448945610?utm_source=github_status&utm_medium=notification).

**Comment by Fuco1** [comment]
Do I understand it right that byte compiling the code makes it not work? :D That's quite funny.

**Comment by DamienCassou** [comment]
Matus Goljer <notifications@github.com> writes:
> Do I understand it right that byte compiling the code makes it not
> work? :D

yes, and I don't know wny. Maybe a bug in Emacs 26.1.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by Fuco1** [comment]
Previously the macro `(elsa-make-type Keyword)` expanded right to an actual instance of the class.  This was not a problem because it was static in the vector representation.

With the new representation there is apparently some dynamic element and we can not do this at compile time, otherwise the type-checks wont work.

So I've change the macro to only expand lazily to a function call which when called will actually produce a new instance of the class.

This seems to fix a bunch of errors but now I'm getting new ones.  In any case, I think the root cause will be the same: I've tried to optimize by compiling as much as possible during the byte-compile step and new EIEIO broke this.

**Comment by Fuco1** [comment]
I think da9a606 fixes this.
