### ISSUE TITLE
M-x entrypoint

### ISSUE THREAD

**Issue by nickdrozd** [emacs-elsa/Elsa#67]
Sorry if I missed it in the readme, but is there any single command to lint a file / buffer? Before messing around with any configuration, I'd like to do run something like `elsa-analyze-buffer` and get the results opened in another buffer.

If not, then this is a feature request :)

For reference, something like `package-lint-current-buffer` is what I have in mind.

**Comment by Fuco1** [comment]
The package is not ment to be used interactively from emacs because keeping the isolation and load paths and all that proper is a very difficult job in an environment where everything is global.

If you load all the things manually and then evaluate 

    (elsa-process-file (buffer-file-name))

that should give you have the state, you can access errors with `(oref state errors)`.  It will not follow require forms so some type annotations might be missing in which case you will need to run the above form in all the dependency buffers as well.

But the best way to go is to set up Cask and flycheck as described in the readme.

**Comment by Fuco1** [comment]
It is also very unlikely that we will support any other way of execution than from the command line, be it cask or a stand-alone binary.  There is simply too much interference to re-use the same process.

**Comment by Fuco1** [comment]
There is now a helper `elsa-process-form` which you can run interactively or in M-x eval as `(elsa-process-form)` which will process form at point and return the analyzed structure.

I use this for debugging so the user must make sure everything is loaded properly.

It currently does not report the errors though.
